"""Configuration package for RAG Chatbot."""

from .settings import (
    PROJECT_ROOT,
    DATA_DIR,
    DOCUMENTS_DIR,
    VECTOR_STORES_DIR,
    LOGS_DIR,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_EMBEDDING_TYPE,
    HUGGINGFACE_MODEL,
    DEFAULT_LLM_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_MAX_TOKENS,
    DEFAULT_RETRIEVAL_K,
    DEFAULT_MEMORY_TYPE,
    DEFAULT_WINDOW_SIZE,
    SUPPORTED_FILE_TYPES,
)

__all__ = [
    "PROJECT_ROOT",
    "DATA_DIR",
    "DOCUMENTS_DIR",
    "VECTOR_STORES_DIR",
    "LOGS_DIR",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_EMBEDDING_TYPE",
    "HUGGINGFACE_MODEL",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_RETRIEVAL_K",
    "DEFAULT_MEMORY_TYPE",
    "DEFAULT_WINDOW_SIZE",
    "SUPPORTED_FILE_TYPES",
]
